### PR TITLE
improving docs, adding .idea to gitignore

### PR DESCRIPTION
**Pull request by jposada202020**
As title describes

Built locally to verify

### CODE REVIEW

**Review by ladyada — APPROVED** [review]

**Comment by jepler** [comment]
I don't know what ".idea" is, so this is based on my guess, but: please consider: for files created by your particular development environment, you can put the patterns in a "global ignore" file so that they are ignored in every git repository you place on your system.

One philosophy of .gitignore is that the project one is for files created by interacting with the project in "the standard way", like building and testing the software.  An advantage of this philosophy is that it's not scalable to put the patterns for _every development environment_ in _every git repo_, especially since having many patterns can slow git down (though this is much better than it used to be, at least on linux), and you don't have to make a special request in each project you want to contribute to!

In the CircuitPython modules, we like for all the various files like .gitignore, .github/workflows/build.yml, etc., to have exactly the same content whenever possible, so that doing mass updates of these files can be done by simple patches, so we also think it could reduce effort for us in the long run.

For more details and how-to, see https://stackoverflow.com/questions/7335420/global-git-ignore https://docs.github.com/en/github/getting-started-with-github/ignoring-files#configuring-ignored-files-for-all-repositories-on-your-computer and other resources that an internet search can find!

**Comment by jposada202020** [comment]
@jepler Valid Points. Thanks
However this is included in other libraries already as well. Just to put a few

* ltr390
https://github.com/adafruit/Adafruit_CircuitPython_LTR390/blob/df431ed7dd08e116abe14f5b684f813b19448153/.gitignore#L6

* AD7410
https://github.com/adafruit/Adafruit_CircuitPython_ADT7410/blob/a5eae664530a1bc01f1819a140cffd1e6ed3ebfe/.gitignore#L6

* irremote
https://github.com/adafruit/Adafruit_CircuitPython_IRRemote/blob/d8260f2fe2a8b3e874320483060756dce4c2a9ec/.gitignore#L6

* Blinka
https://github.com/adafruit/Adafruit_Blinka/blob/16848c1255d8b323a88500f11923a3b39777cf0b/.gitignore#L2

**Comment by kattni** [comment]
To clarify, @jposada202020 @jepler, `.idea` is the directory created when you start PyCharm from within a working directory. I use PyCharm, and am definitely responsible for adding it to some of the libraries. It is fine to add it for now if you run into it. 

I am going to file an issue on `cookiecutter` to suggest updating our .gitignore to include the additional files added by popular IDEs, as we are running into this more often with more diverse folks contributing to the libraries. I feel we would benefit from a more robust `.gitignore` so folks are not forced to deal with these things locally.

**Comment by jposada202020** [comment]
@kattni thanks for the comments. will do

**Pull request merged**
